/* eslint-disable react-refresh/only-export-components */
/**
 * CalcShell — Universal wrapper applied to EVERY calculator
 * Provides: Reset, Copy, Share URL, Formula toggle, PDF export, FAQ
 */
import { useState, useCallback } from "react";
import { RotateCcw, Copy, Share2, BookOpen, Download, Check, Link, X } from "lucide-react";
import { InsightBox } from '@/components/ui/InsightBox';
import { Breakdown }  from '@/components/ui/Breakdown';

/* ── URL State sharing ─────────────────────────────────────────── */
export function buildShareURL(params) {
  const url = new URL(window.location.href);
  Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, String(v)));
  return url.toString();
}

export function readURLParams() {
  const p = new URLSearchParams(window.location.search);
  const out = {};
  for (const [k, v] of p.entries()) out[k] = v;
  return out;
}

/* ── PDF export via print ──────────────────────────────────────── */
export function exportToPDF(title) {
  const w = window.open("", "_blank");
  if (!w) return;
  const content = document.getElementById("calc-result-area")?.innerHTML || "";
  w.document.write(`
    <!DOCTYPE html><html><head>
    <title>${title} — Calculators Point</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #0f172a; }
      h1 { color: #4361ee; font-size: 24px; margin-bottom: 8px; }
      .sub { color: #64748b; font-size: 13px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      td, th { padding: 10px 14px; border: 1px solid #e2e8f0; font-size: 13px; }
      th { background: #f1f5f9; font-weight: 700; text-align: left; }
      .highlight { background: #dbeafe; font-weight: 700; color: #1e40af; }
      .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    </style></head><body>
    <h1>${title}</h1>
    <div class="sub">Generated by calculatorspoint.com on ${new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</div>
    <div>${content}</div>
    <div class="footer">⚠️ Results are for informational purposes only. Always verify with a professional.</div>
    </body></html>
  `);
  w.document.close();
  setTimeout(() => { w.print(); w.close(); }, 500);
}

/* ── CSV export ────────────────────────────────────────────────── */
export function exportToCSV(rows, filename = "Calculators Point-result") {
  if (!rows?.length) return;
  const csv = rows.map(r => `"${r.label}","${r.value}"`).join("\n");
  const blob = new Blob(["Label,Value\n" + csv], { type: "text/csv" });
  const a = document.createElement("a"); a.href = URL.createObjectURL(blob);
  a.download = filename + ".csv"; a.click(); URL.revokeObjectURL(a.href);
}

/* ── Action toolbar (shared by every calculator) ───────────────── */
export function CalcToolbar({ title, onReset, result, shareParams, formulaContent, faqItems }) {
  const [copied,      setCopied]      = useState(false);
  const [showFrm,     setShowFrm]     = useState(false);
  const [showFAQ,     setShowFAQ]     = useState(false);
  const [shareCopied, setShareCopied] = useState(false);

  const copyResult = useCallback(() => {
    const txt = result?.primary?.value || "";
    navigator.clipboard.writeText(txt).catch(() => {});
    setCopied(true); setTimeout(() => setCopied(false), 1800);
  }, [result]);

  const copyShare = useCallback(() => {
    const url = shareParams ? buildShareURL(shareParams) : window.location.href;
    navigator.clipboard.writeText(url).catch(() => {});
    setShareCopied(true); setTimeout(() => setShareCopied(false), 2000);
  }, [shareParams]);

  const doExportPDF = () => exportToPDF(title || "Calculator");
  const doExportCSV = () => result?.breakdowns?.length && exportToCSV(result.breakdowns, title?.toLowerCase().replace(/\s+/g,"-"));

  return (
    <div>
      {/* Toolbar */}
      <div style={{ display:"flex", flexWrap:"wrap", gap:6, marginBottom:16, paddingBottom:14, borderBottom:"1px solid var(--bord2)" }}>
        {/* Reset */}
        <button onClick={onReset} className="calc-tool-btn danger" title="Reset all inputs">
          <RotateCcw size={12}/> Reset
        </button>

        {/* Copy result */}
        {result?.primary?.value && (
          <button onClick={copyResult} className={`calc-tool-btn ${copied ? "active success" : ""}`}>
            {copied ? <Check size={12}/> : <Copy size={12}/>}
            {copied ? "Copied!" : "Copy Result"}
          </button>
        )}

        {/* Share URL */}
        <button onClick={copyShare} className={`calc-tool-btn ${shareCopied ? "active" : ""}`}>
          {shareCopied ? <Check size={12}/> : <Link size={12}/>}
          {shareCopied ? "Link Copied!" : "Share"}
        </button>

        {/* Formula */}
        {formulaContent && (
          <button onClick={() => setShowFrm(!showFrm)} className={`calc-tool-btn ${showFrm ? "active" : ""}`}>
            <BookOpen size={12}/> {showFrm ? "Hide" : "Formula"}
          </button>
        )}

        {/* Export PDF */}
        <button onClick={doExportPDF} className="calc-tool-btn">
          <Download size={12}/> PDF
        </button>

        {/* Export CSV */}
        {result?.breakdowns?.length > 0 && (
          <button onClick={doExportCSV} className="calc-tool-btn success">
            <Download size={12}/> CSV
          </button>
        )}

        {/* FAQ */}
        {faqItems?.length > 0 && (
          <button onClick={() => setShowFAQ(!showFAQ)}
            className={`calc-tool-btn ${showFAQ ? "active" : ""}`}
            style={{ marginLeft:"auto" }}>
            ❓ {showFAQ ? "Hide FAQ" : "FAQ"}
          </button>
        )}
      </div>

      {/* Formula panel */}
      {showFrm && formulaContent && (
        <div className="formula-box" style={{ marginBottom: 16 }}>
          <div className="formula-box-head">
            <span className="formula-box-label">📘 Formula &amp; Method</span>
            <button onClick={() => setShowFrm(false)}
              style={{ color:"var(--text3)", background:"none", border:"none", cursor:"pointer", display:"flex", alignItems:"center" }}>
              <X size={14}/>
            </button>
          </div>
          <div className="formula-box-body">{formulaContent}</div>
        </div>
      )}

      {/* FAQ panel */}
      {showFAQ && faqItems?.length > 0 && (
        <div style={{ marginBottom:16 }}>
          <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:10, paddingBottom:8, borderBottom:"1px solid var(--border)" }}>
            <p style={{ fontSize:12, fontWeight:800, textTransform:"uppercase", letterSpacing:".06em", color:"var(--text3)", display:"flex", alignItems:"center", gap:6 }}>
              ❓ Frequently Asked
            </p>
            <button onClick={() => setShowFAQ(false)}
              style={{ color:"var(--text3)", background:"none", border:"none", cursor:"pointer", display:"flex", alignItems:"center" }}>
              <X size={14}/>
            </button>
          </div>
          {faqItems.map((faq, i) => (
            <details key={i} style={{ marginBottom:6 }}>
              <summary style={{ cursor:"pointer", fontWeight:600, fontSize:13, padding:"10px 14px", background:"var(--surf2)", borderRadius:"var(--r-md)", color:"var(--text)", listStyle:"none", display:"flex", justifyContent:"space-between", userSelect:"none" }}>
                {faq.q} <span style={{ color:"var(--brand)", fontSize:18 }}>+</span>
              </summary>
              <div style={{ padding:"10px 14px", fontSize:13, lineHeight:1.75, color:"var(--text2)", background:"var(--surface)", border:"1px solid var(--bord2)", borderTop:"none", borderRadius:"0 0 var(--r-md) var(--r-md)" }}>
                {faq.a}
              </div>
            </details>
          ))}
        </div>
      )}
    </div>
  );
}

/* ── Result area (for PDF export) ──────────────────────────────── */
export function ResultArea({ children }) {
  return <div id="calc-result-area">{children}</div>;
}
