import { lazy } from "react";

const Finance = {
  EMIForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.EMIForm || (() => null) }))),
  CompoundForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.CompoundForm || (() => null) }))),
  SIPForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.SIPForm || (() => null) }))),
  SimpleInterestForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.SimpleInterestForm || (() => null) }))),
  ROIForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.ROIForm || (() => null) }))),
  SalaryForm: lazy(() => import("../../../modules/finance/salary/SalaryCalculator").then((m: any) => ({ default: m.SalaryCalculator || (() => null) }))),
  TaxForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.TaxForm || (() => null) }))),
  DiscountForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.DiscountForm || (() => null) }))),
  ProfitMarginForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.ProfitMarginForm || (() => null) }))),
  BreakEvenForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.BreakEvenForm || (() => null) }))),
  GSTForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.GSTForm || (() => null) }))),
  PPFForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.PPFForm || (() => null) }))),
  TipForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.TipForm || (() => null) }))),
  MortgageForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.MortgageForm || (() => null) }))),
  RetirementForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.RetirementPlanForm || (() => null) }))),
  NPSForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.NPSForm || (() => null) }))),
  EPFForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.EPFForm || (() => null) }))),
  FDForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.FDForm || (() => null) }))),
  LoanCompareForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.LoanCompareForm || (() => null) }))),
  StockReturnForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.StockReturnForm || (() => null) }))),
  NPVForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.NPVForm || (() => null) }))),
  PortfolioRebalanceForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.PortfolioRebalanceForm || (() => null) }))),
  DividendYieldForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.DividendYieldForm || (() => null) }))),
  MortgagePayoffForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.MortgagePayoffForm || (() => null) }))),
  HouseAffordabilityForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.HouseAffordabilityForm || (() => null) }))),
  RentVsBuyForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.RentVsBuyForm || (() => null) }))),
  APRForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.APRForm || (() => null) }))),
  AutoLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.AutoLoanForm || (() => null) }))),
  PersonalLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.PersonalLoanForm || (() => null) }))),
  StudentLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.StudentLoanForm || (() => null) }))),
  CreditCardForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.CreditCardForm || (() => null) }))),
  DebtPayoffForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.DebtPayoffForm || (() => null) }))),
  Calculator401kForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.Calculator401kForm || (() => null) }))),
  CommissionForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.CommissionForm || (() => null) }))),
  DepreciationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.DepreciationForm || (() => null) }))),
  BudgetForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.BudgetForm || (() => null) }))),
  PresentValueForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.PresentValueForm || (() => null) }))),
  IRRForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.IRRForm || (() => null) }))),
  DownPaymentForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.DownPaymentForm || (() => null) }))),
  CollegeCostForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.CollegeCostForm || (() => null) }))),
  HELOCForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.HELOCForm || (() => null) }))),
  AutoLeaseForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AutoLeaseForm || (() => null) }))),
  BondForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.BondForm || (() => null) }))),
  CDForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.CDForm || (() => null) }))),
  RothIRAForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.RothIRAForm || (() => null) }))),
  AnnuityForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AnnuityForm || (() => null) }))),
  PensionForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.PensionForm || (() => null) }))),
  SocialSecurityForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.SocialSecurityForm || (() => null) }))),
  RMDForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.RMDForm || (() => null) }))),
  EstateTaxForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.EstateTaxForm || (() => null) }))),
  MarriageTaxForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.MarriageTaxForm || (() => null) }))),
  BoatLoanForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.BoatLoanForm || (() => null) }))),
  DebtConsolidationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.DebtConsolidationForm || (() => null) }))),
  FutureValueForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.FutureValueForm || (() => null) }))),
  AverageReturnForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AverageReturnForm || (() => null) }))),
  AmortizationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AmortizationForm || (() => null) }))),
  TVMForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.TVMForm || (() => null) }))),
  InvestmentCalcForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.InvestmentCalcForm || (() => null) }))),
  GenericLoanForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.GenericLoanForm || (() => null) }))),
};

export const financeForms = {
  "loan-emi-calculator":               Finance.EMIForm,
  "mortgage-calculator":               Finance.MortgageForm,
  "compound-interest-calculator":      Finance.CompoundForm,
  "sip-calculator":                    Finance.SIPForm,
  "simple-interest-calculator":        Finance.SimpleInterestForm,
  "roi-calculator":                    Finance.ROIForm,
  "salary-calculator":                 Finance.SalaryForm,
  "discount-calculator":               Finance.DiscountForm,
  "profit-margin-calculator":          Finance.ProfitMarginForm,
  "break-even-calculator":             Finance.BreakEvenForm,
  "tax-calculator":                    Finance.TaxForm,
  "tip-calculator":                    Finance.TipForm,
  "gst-calculator":                    Finance.GSTForm,
  "ppf-calculator":                    Finance.PPFForm,
  "retirement-calculator":             Finance.RetirementForm,
  "nps-calculator":                    Finance.NPSForm,
  "epf-calculator":                    Finance.EPFForm,
  "fd-calculator":                     Finance.FDForm,
  "loan-comparison-calculator":        Finance.LoanCompareForm,
  "stock-return-calculator":           Finance.StockReturnForm,
  "npv-calculator":                    Finance.NPVForm,
  "portfolio-rebalance-calculator":    Finance.PortfolioRebalanceForm,
  "dividend-yield-calculator":         Finance.DividendYieldForm,
  "mortgage-payoff-calculator":        Finance.MortgagePayoffForm,
  "house-affordability-calculator":    Finance.HouseAffordabilityForm,
  "rent-vs-buy-calculator":            Finance.RentVsBuyForm,
  "apr-calculator":                    Finance.APRForm,
  "auto-loan-calculator":              Finance.AutoLoanForm,
  "personal-loan-calculator":          Finance.PersonalLoanForm,
  "student-loan-calculator":           Finance.StudentLoanForm,
  "credit-card-calculator":            Finance.CreditCardForm,
  "debt-payoff-calculator":            Finance.DebtPayoffForm,
  "401k-calculator":                   Finance.Calculator401kForm,
  "commission-calculator":             Finance.CommissionForm,
  "depreciation-calculator":           Finance.DepreciationForm,
  "budget-calculator":                 Finance.BudgetForm,
  "present-value-calculator":          Finance.PresentValueForm,
  "irr-calculator":                    Finance.IRRForm,
  "down-payment-calculator":           Finance.DownPaymentForm,
  "college-cost-calculator":           Finance.CollegeCostForm,
  "heloc-calculator":                  Finance.HELOCForm,
  "auto-lease-calculator":             Finance.AutoLeaseForm,
  "bond-calculator":                   Finance.BondForm,
  "cd-calculator":                     Finance.CDForm,
  "roth-ira-calculator":               Finance.RothIRAForm,
  "annuity-calculator":                Finance.AnnuityForm,
  "pension-calculator":                Finance.PensionForm,
  "social-security-calculator":        Finance.SocialSecurityForm,
  "rmd-calculator":                    Finance.RMDForm,
  "estate-tax-calculator":             Finance.EstateTaxForm,
  "marriage-tax-calculator":           Finance.MarriageTaxForm,
  "boat-loan-calculator":              Finance.BoatLoanForm,
  "debt-consolidation-calculator":     Finance.DebtConsolidationForm,
  "future-value-calculator":           Finance.FutureValueForm,
  "average-return-calculator":         Finance.AverageReturnForm,
  "amortization-calculator":           Finance.AmortizationForm,
  "tvm-calculator":                    Finance.TVMForm,
  "investment-calculator":             Finance.InvestmentCalcForm,
  "loan-calculator":                   Finance.GenericLoanForm,
};
