import { lazy } from "react";

const Finance = {
  EMIForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.EMIForm }))),
  CompoundForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.CompoundForm }))),
  SIPForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.SIPForm }))),
  SimpleInterestForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.SimpleInterestForm }))),
  ROIForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.ROIForm }))),
  SalaryForm: lazy(() => import("../../../modules/finance/salary/SalaryCalculator.tsx").then((m: any) => ({ default: m.SalaryCalculator }))),
  TaxForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.TaxForm }))),
  DiscountForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.DiscountForm }))),
  ProfitMarginForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.ProfitMarginForm }))),
  BreakEvenForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.BreakEvenForm }))),
  GSTForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.GSTForm }))),
  PPFForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.PPFForm }))),
  TipForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.TipForm }))),
  MortgageForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.MortgageForm }))),
  RetirementForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.RetirementPlanForm }))),
  NPSForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.NPSForm }))),
  EPFForm: lazy(() => import('../forms/RetirementForms').then((m: any) => ({ default: m.EPFForm }))),
  FDForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.FDForm }))),
  LoanCompareForm: lazy(() => import('../forms/CoreFinanceForms').then((m: any) => ({ default: m.LoanCompareForm }))),
  StockReturnForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.StockReturnForm }))),
  NPVForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.NPVForm }))),
  PortfolioRebalanceForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.PortfolioRebalanceForm }))),
  DividendYieldForm: lazy(() => import('../forms/InvestmentForms').then((m: any) => ({ default: m.DividendYieldForm }))),
  MortgagePayoffForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.MortgagePayoffForm }))),
  HouseAffordabilityForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.HouseAffordabilityForm }))),
  RentVsBuyForm: lazy(() => import('../forms/MortgageForms').then((m: any) => ({ default: m.RentVsBuyForm }))),
  APRForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.APRForm }))),
  AutoLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.AutoLoanForm }))),
  PersonalLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.PersonalLoanForm }))),
  StudentLoanForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.StudentLoanForm }))),
  CreditCardForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.CreditCardForm }))),
  DebtPayoffForm: lazy(() => import('../forms/LoanDebtForms').then((m: any) => ({ default: m.DebtPayoffForm }))),
  Calculator401kForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.Calculator401kForm }))),
  CommissionForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.CommissionForm }))),
  DepreciationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.DepreciationForm }))),
  BudgetForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.BudgetForm }))),
  PresentValueForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.PresentValueForm }))),
  IRRForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.IRRForm }))),
  DownPaymentForm: lazy(() => import('../forms/ExtraFinanceForms').then((m: any) => ({ default: m.DownPaymentForm }))),
  CollegeCostForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.CollegeCostForm }))),
  HELOCForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.HELOCForm }))),
  AutoLeaseForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AutoLeaseForm }))),
  BondForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.BondForm }))),
  CDForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.CDForm }))),
  RothIRAForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.RothIRAForm }))),
  AnnuityForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AnnuityForm }))),
  PensionForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.PensionForm }))),
  SocialSecurityForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.SocialSecurityForm }))),
  RMDForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.RMDForm }))),
  EstateTaxForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.EstateTaxForm }))),
  MarriageTaxForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.MarriageTaxForm }))),
  BoatLoanForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.BoatLoanForm }))),
  DebtConsolidationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.DebtConsolidationForm }))),
  FutureValueForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.FutureValueForm }))),
  AverageReturnForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AverageReturnForm }))),
  AmortizationForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.AmortizationForm }))),
  TVMForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.TVMForm }))),
  InvestmentCalcForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.InvestmentCalcForm }))),
  GenericLoanForm: lazy(() => import('../forms/FinanceFormsNew').then((m: any) => ({ default: m.GenericLoanForm }))),
};

export const financeForms = {
  "loan-emi-calculator":               Finance.EMIForm,
  "mortgage-calculator":               Finance.MortgageForm,
  "compound-interest-calculator":      Finance.CompoundForm,
  "sip-calculator":                    Finance.SIPForm,
  "simple-interest-calculator":        Finance.SimpleInterestForm,
  "roi-calculator":                    Finance.ROIForm,
  "salary-calculator":                 Finance.SalaryForm,
  "discount-calculator":               Finance.DiscountForm,
  "profit-margin-calculator":          Finance.ProfitMarginForm,
  "break-even-calculator":             Finance.BreakEvenForm,
  "tax-calculator":                    Finance.TaxForm,
  "tip-calculator":                    Finance.TipForm,
  "gst-calculator":                    Finance.GSTForm,
  "ppf-calculator":                    Finance.PPFForm,
  "retirement-calculator":             Finance.RetirementForm,
  "nps-calculator":                    Finance.NPSForm,
  "epf-calculator":                    Finance.EPFForm,
  "fd-calculator":                     Finance.FDForm,
  "loan-comparison-calculator":        Finance.LoanCompareForm,
  "stock-return-calculator":           Finance.StockReturnForm,
  "npv-calculator":                    Finance.NPVForm,
  "portfolio-rebalance-calculator":    Finance.PortfolioRebalanceForm,
  "dividend-yield-calculator":         Finance.DividendYieldForm,
  "mortgage-payoff-calculator":        Finance.MortgagePayoffForm,
  "house-affordability-calculator":    Finance.HouseAffordabilityForm,
  "rent-vs-buy-calculator":            Finance.RentVsBuyForm,
  "apr-calculator":                    Finance.APRForm,
  "auto-loan-calculator":              Finance.AutoLoanForm,
  "personal-loan-calculator":          Finance.PersonalLoanForm,
  "student-loan-calculator":           Finance.StudentLoanForm,
  "credit-card-calculator":            Finance.CreditCardForm,
  "debt-payoff-calculator":            Finance.DebtPayoffForm,
  "401k-calculator":                   Finance.Calculator401kForm,
  "commission-calculator":             Finance.CommissionForm,
  "depreciation-calculator":           Finance.DepreciationForm,
  "budget-calculator":                 Finance.BudgetForm,
  "present-value-calculator":          Finance.PresentValueForm,
  "irr-calculator":                    Finance.IRRForm,
  "down-payment-calculator":           Finance.DownPaymentForm,
  "college-cost-calculator":           Finance.CollegeCostForm,
  "heloc-calculator":                  Finance.HELOCForm,
  "auto-lease-calculator":             Finance.AutoLeaseForm,
  "bond-calculator":                   Finance.BondForm,
  "cd-calculator":                     Finance.CDForm,
  "roth-ira-calculator":               Finance.RothIRAForm,
  "annuity-calculator":                Finance.AnnuityForm,
  "pension-calculator":                Finance.PensionForm,
  "social-security-calculator":        Finance.SocialSecurityForm,
  "rmd-calculator":                    Finance.RMDForm,
  "estate-tax-calculator":             Finance.EstateTaxForm,
  "marriage-tax-calculator":           Finance.MarriageTaxForm,
  "boat-loan-calculator":              Finance.BoatLoanForm,
  "debt-consolidation-calculator":     Finance.DebtConsolidationForm,
  "future-value-calculator":           Finance.FutureValueForm,
  "average-return-calculator":         Finance.AverageReturnForm,
  "amortization-calculator":           Finance.AmortizationForm,
  "tvm-calculator":                    Finance.TVMForm,
  "investment-calculator":             Finance.InvestmentCalcForm,
  "loan-calculator":                   Finance.GenericLoanForm,
};
