import { lazy } from "react";

const Health = {
  BMIForm: lazy(() => import("../../../modules/health/bmi/BMICalculator.tsx").then((m: any) => ({ default: m.BMICalculator }))),
  CalorieForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.CalorieForm }))),
  BMRForm: lazy(() => import("../../../modules/health/bmr/BMRCalculator.tsx").then((m: any) => ({ default: m.BMRCalculator }))),
  BodyFatForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BodyFatForm }))),
  IdealWeightForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.IdealWeightForm }))),
  MacroForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.MacroForm }))),
  WaterForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.WaterForm }))),
  HeartRateForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.HeartRateForm }))),
  PregnancyForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.PregnancyForm }))),
  OneRMForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.OneRMForm }))),
  CaloriesBurnedForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.CaloriesBurnedForm }))),
  SleepForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.SleepForm }))),
  PeriodCalc: lazy(() => import('../../../modules/health/women-health/PeriodCalculator') as Promise<{default: React.ComponentType<any>}>),
  BSAForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BSAForm }))),
  BACForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BACForm }))),
  LeanBodyMassForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.LeanBodyMassForm }))),
  ProteinForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.ProteinForm }))),
  HealthyWeightForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.HealthyWeightForm }))),
  FatIntakeForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.FatIntakeForm }))),
  ArmyBodyFatForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.ArmyBodyFatForm }))),
  ConceptionForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.ConceptionForm }))),
  BodyTypeForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.BodyTypeForm }))),
  GFRForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.GFRForm }))),
};

export const healthForms = {
  "bmi-calculator":                    Health.BMIForm,
  "calorie-calculator":                Health.CalorieForm,
  "bmr-calculator":                    Health.BMRForm,
  "body-fat-calculator":               Health.BodyFatForm,
  "ideal-weight-calculator":           Health.IdealWeightForm,
  "macro-calculator":                  Health.MacroForm,
  "water-intake-calculator":           Health.WaterForm,
  "heart-rate-calculator":             Health.HeartRateForm,
  "pregnancy-due-date":                Health.PregnancyForm,
  "one-rep-max-calculator":            Health.OneRMForm,
  "calories-burned-calculator":        Health.CaloriesBurnedForm,
  "sleep-calculator":                  Health.SleepForm,
  "period-calculator":                 Health.PeriodCalc,
  "ovulation-calculator":              Health.PeriodCalc,
  "fertility-window-calculator":       Health.PeriodCalc,
  "implantation-calculator":           Health.PeriodCalc,
  "bsa-calculator":                    Health.BSAForm,
  "bac-calculator":                    Health.BACForm,
  "lean-body-mass-calculator":         Health.LeanBodyMassForm,
  "protein-calculator":                Health.ProteinForm,
  "healthy-weight-calculator":         Health.HealthyWeightForm,
  "fat-intake-calculator":             Health.FatIntakeForm,
  "army-body-fat-calculator":          Health.ArmyBodyFatForm,
  "conception-calculator":             Health.ConceptionForm,
  "body-type-calculator":              Health.BodyTypeForm,
  "gfr-calculator":                    Health.GFRForm,
};
