import { lazy } from "react";

const Health = {
  BMIForm: lazy(() => import("../../../modules/health/bmi/BMICalculator").then((m: any) => ({ default: m.BMICalculator || (() => null) }))),
  CalorieForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.CalorieForm || (() => null) }))),
  BMRForm: lazy(() => import("../../../modules/health/bmr/BMRCalculator").then((m: any) => ({ default: m.BMRCalculator || (() => null) }))),
  BodyFatForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BodyFatForm || (() => null) }))),
  IdealWeightForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.IdealWeightForm || (() => null) }))),
  MacroForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.MacroForm || (() => null) }))),
  WaterForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.WaterForm || (() => null) }))),
  HeartRateForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.HeartRateForm || (() => null) }))),
  PregnancyForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.PregnancyForm || (() => null) }))),
  OneRMForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.OneRMForm || (() => null) }))),
  CaloriesBurnedForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.CaloriesBurnedForm || (() => null) }))),
  SleepForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.SleepForm || (() => null) }))),
  PeriodCalc: lazy(() => import('../../../modules/health/women-health/PeriodCalculator') as Promise<{default: React.ComponentType<any>}>),
  BSAForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BSAForm || (() => null) }))),
  BACForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.BACForm || (() => null) }))),
  LeanBodyMassForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.LeanBodyMassForm || (() => null) }))),
  ProteinForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.ProteinForm || (() => null) }))),
  HealthyWeightForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.HealthyWeightForm || (() => null) }))),
  FatIntakeForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.FatIntakeForm || (() => null) }))),
  ArmyBodyFatForm: lazy(() => import('../forms/HealthForms').then((m: any) => ({ default: m.ArmyBodyFatForm || (() => null) }))),
  ConceptionForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.ConceptionForm || (() => null) }))),
  BodyTypeForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.BodyTypeForm || (() => null) }))),
  GFRForm: lazy(() => import("../forms/HealthForms").then((m: any) => ({ default: m.GFRForm || (() => null) }))),
};

export const healthForms = {
  "bmi-calculator":                    Health.BMIForm,
  "calorie-calculator":                Health.CalorieForm,
  "bmr-calculator":                    Health.BMRForm,
  "body-fat-calculator":               Health.BodyFatForm,
  "ideal-weight-calculator":           Health.IdealWeightForm,
  "macro-calculator":                  Health.MacroForm,
  "water-intake-calculator":           Health.WaterForm,
  "heart-rate-calculator":             Health.HeartRateForm,
  "pregnancy-due-date":                Health.PregnancyForm,
  "one-rep-max-calculator":            Health.OneRMForm,
  "calories-burned-calculator":        Health.CaloriesBurnedForm,
  "sleep-calculator":                  Health.SleepForm,
  "period-calculator":                 Health.PeriodCalc,
  "ovulation-calculator":              Health.PeriodCalc,
  "fertility-window-calculator":       Health.PeriodCalc,
  "implantation-calculator":           Health.PeriodCalc,
  "bsa-calculator":                    Health.BSAForm,
  "bac-calculator":                    Health.BACForm,
  "lean-body-mass-calculator":         Health.LeanBodyMassForm,
  "protein-calculator":                Health.ProteinForm,
  "healthy-weight-calculator":         Health.HealthyWeightForm,
  "fat-intake-calculator":             Health.FatIntakeForm,
  "army-body-fat-calculator":          Health.ArmyBodyFatForm,
  "conception-calculator":             Health.ConceptionForm,
  "body-type-calculator":              Health.BodyTypeForm,
  "gfr-calculator":                    Health.GFRForm,
};
