import { lazy } from "react";

const MathCalcs = {
  PercentageForm: lazy(() => import("../../../modules/math/percentage/PercentageCalculator").then((m: any) => ({ default: m.PercentageCalculator || (() => null) }))),
  ScientificForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ScientificForm || (() => null) }))),
  StatsForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.StatsForm || (() => null) }))),
  QuadraticForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.QuadraticForm || (() => null) }))),
  PythagoreanForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PythagoreanForm || (() => null) }))),
  FractionForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.FractionForm || (() => null) }))),
  GPAForm: lazy(() => import("../../../modules/education/gpa/GPACalculator").then((m: any) => ({ default: m.GPACalculator || (() => null) }))),
  CGPAForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.CGPAForm || (() => null) }))),
  PrimeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PrimeForm || (() => null) }))),
  LogForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LogForm || (() => null) }))),
  RatioForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RatioForm || (() => null) }))),
  ReadingTimeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ReadingTimeForm || (() => null) }))),
  LCMGCFForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LCMGCFForm || (() => null) }))),
  FactorForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.FactorForm || (() => null) }))),
  ExponentForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ExponentForm || (() => null) }))),
  RootForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RootForm || (() => null) }))),
  TriangleForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.TriangleForm || (() => null) }))),
  CircleForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.CircleForm || (() => null) }))),
  VolumeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.VolumeForm || (() => null) }))),
  SurfaceAreaForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.SurfaceAreaForm || (() => null) }))),
  ZScoreForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ZScoreForm || (() => null) }))),
  ConfidenceIntervalForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ConfidenceIntervalForm || (() => null) }))),
  SampleSizeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.SampleSizeForm || (() => null) }))),
  PermCombForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PermCombForm || (() => null) }))),
  ProbabilityForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ProbabilityForm || (() => null) }))),
  BinaryForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.BinaryForm || (() => null) }))),
  NumberSequenceForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.NumberSequenceForm || (() => null) }))),
  AverageForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.AverageForm || (() => null) }))),
  MatrixForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.MatrixForm || (() => null) }))),
  LinearEquationForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LinearEquationForm || (() => null) }))),
  RandomNumberForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RandomNumberForm || (() => null) }))),
  PercentErrorForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PercentErrorForm || (() => null) }))),
  DistanceForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.DistanceForm || (() => null) }))),
};

export const mathForms = {
  "percentage-calculator":             MathCalcs.PercentageForm,
  "scientific-calculator":             MathCalcs.ScientificForm,
  "statistics-calculator":             MathCalcs.StatsForm,
  "quadratic-calculator":              MathCalcs.QuadraticForm,
  "pythagorean-calculator":            MathCalcs.PythagoreanForm,
  "fraction-calculator":               MathCalcs.FractionForm,
  "prime-number-checker":              MathCalcs.PrimeForm,
  "logarithm-calculator":              MathCalcs.LogForm,
  "ratio-calculator":                  MathCalcs.RatioForm,
  "reading-time-calculator":           MathCalcs.ReadingTimeForm,
  "gpa-calculator":                    MathCalcs.GPAForm,
  "cgpa-percentage-calculator":        MathCalcs.CGPAForm,
  "lcm-gcf-calculator":                MathCalcs.LCMGCFForm,
  "factor-calculator":                 MathCalcs.FactorForm,
  "exponent-calculator":               MathCalcs.ExponentForm,
  "root-calculator":                   MathCalcs.RootForm,
  "triangle-calculator":               MathCalcs.TriangleForm,
  "circle-calculator":                 MathCalcs.CircleForm,
  "volume-calculator":                 MathCalcs.VolumeForm,
  "surface-area-calculator":           MathCalcs.SurfaceAreaForm,
  "z-score-calculator":                MathCalcs.ZScoreForm,
  "confidence-interval-calculator":    MathCalcs.ConfidenceIntervalForm,
  "sample-size-calculator":            MathCalcs.SampleSizeForm,
  "permutation-combination-calculator": MathCalcs.PermCombForm,
  "probability-calculator":            MathCalcs.ProbabilityForm,
  "binary-calculator":                 MathCalcs.BinaryForm,
  "number-sequence-calculator":        MathCalcs.NumberSequenceForm,
  "average-calculator":                MathCalcs.AverageForm,
  "matrix-calculator":                 MathCalcs.MatrixForm,
  "linear-equation-solver":            MathCalcs.LinearEquationForm,
  "random-number-generator-adv":       MathCalcs.RandomNumberForm,
  "percent-error-calculator":          MathCalcs.PercentErrorForm,
  "distance-calculator":               MathCalcs.DistanceForm,
};
