import { lazy } from "react";

const MathCalcs = {
  PercentageForm: lazy(() => import("../../../modules/math/percentage/PercentageCalculator.tsx").then((m: any) => ({ default: m.PercentageCalculator }))),
  ScientificForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ScientificForm }))),
  StatsForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.StatsForm }))),
  QuadraticForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.QuadraticForm }))),
  PythagoreanForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PythagoreanForm }))),
  FractionForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.FractionForm }))),
  GPAForm: lazy(() => import("../../../modules/education/gpa/GPACalculator.tsx").then((m: any) => ({ default: m.GPACalculator }))),
  CGPAForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.CGPAForm }))),
  PrimeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PrimeForm }))),
  LogForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LogForm }))),
  RatioForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RatioForm }))),
  ReadingTimeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ReadingTimeForm }))),
  LCMGCFForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LCMGCFForm }))),
  FactorForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.FactorForm }))),
  ExponentForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ExponentForm }))),
  RootForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RootForm }))),
  TriangleForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.TriangleForm }))),
  CircleForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.CircleForm }))),
  VolumeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.VolumeForm }))),
  SurfaceAreaForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.SurfaceAreaForm }))),
  ZScoreForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ZScoreForm }))),
  ConfidenceIntervalForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ConfidenceIntervalForm }))),
  SampleSizeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.SampleSizeForm }))),
  PermCombForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PermCombForm }))),
  ProbabilityForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ProbabilityForm }))),
  BinaryForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.BinaryForm }))),
  NumberSequenceForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.NumberSequenceForm }))),
  AverageForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.AverageForm }))),
  MatrixForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.MatrixForm }))),
  LinearEquationForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.LinearEquationForm }))),
  RandomNumberForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.RandomNumberForm }))),
  PercentErrorForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.PercentErrorForm }))),
  DistanceForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.DistanceForm }))),
};

export const mathForms = {
  "percentage-calculator":             MathCalcs.PercentageForm,
  "scientific-calculator":             MathCalcs.ScientificForm,
  "statistics-calculator":             MathCalcs.StatsForm,
  "quadratic-calculator":              MathCalcs.QuadraticForm,
  "pythagorean-calculator":            MathCalcs.PythagoreanForm,
  "fraction-calculator":               MathCalcs.FractionForm,
  "prime-number-checker":              MathCalcs.PrimeForm,
  "logarithm-calculator":              MathCalcs.LogForm,
  "ratio-calculator":                  MathCalcs.RatioForm,
  "reading-time-calculator":           MathCalcs.ReadingTimeForm,
  "gpa-calculator":                    MathCalcs.GPAForm,
  "cgpa-percentage-calculator":        MathCalcs.CGPAForm,
  "lcm-gcf-calculator":                MathCalcs.LCMGCFForm,
  "factor-calculator":                 MathCalcs.FactorForm,
  "exponent-calculator":               MathCalcs.ExponentForm,
  "root-calculator":                   MathCalcs.RootForm,
  "triangle-calculator":               MathCalcs.TriangleForm,
  "circle-calculator":                 MathCalcs.CircleForm,
  "volume-calculator":                 MathCalcs.VolumeForm,
  "surface-area-calculator":           MathCalcs.SurfaceAreaForm,
  "z-score-calculator":                MathCalcs.ZScoreForm,
  "confidence-interval-calculator":    MathCalcs.ConfidenceIntervalForm,
  "sample-size-calculator":            MathCalcs.SampleSizeForm,
  "permutation-combination-calculator": MathCalcs.PermCombForm,
  "probability-calculator":            MathCalcs.ProbabilityForm,
  "binary-calculator":                 MathCalcs.BinaryForm,
  "number-sequence-calculator":        MathCalcs.NumberSequenceForm,
  "average-calculator":                MathCalcs.AverageForm,
  "matrix-calculator":                 MathCalcs.MatrixForm,
  "linear-equation-solver":            MathCalcs.LinearEquationForm,
  "random-number-generator-adv":       MathCalcs.RandomNumberForm,
  "percent-error-calculator":          MathCalcs.PercentErrorForm,
  "distance-calculator":               MathCalcs.DistanceForm,
};
