import { lazy } from "react";

const Utility = {
  UnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.UnitForm || (() => null) }))),
  AreaForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.AreaForm || (() => null) }))),
  TemperatureForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.TemperatureForm || (() => null) }))),
  AgeForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.AgeForm || (() => null) }))),
  DateDiffForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.DateDiffForm || (() => null) }))),
  CountdownForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.CountdownForm || (() => null) }))),
  WorkHoursForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.WorkHoursForm || (() => null) }))),
  FuelForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.FuelForm || (() => null) }))),
  RandomForm: lazy(() => import("../../../modules/everyday/random/RandomGenerator").then((m: any) => ({ default: m.RandomGenerator || (() => null) }))),
  PasswordForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.PasswordForm || (() => null) }))),
  RomanForm: lazy(() => import("../../../modules/conversion/roman/RomanConverter").then((m: any) => ({ default: m.RomanConverter || (() => null) }))),
  WordCountForm: lazy(() => import("../../../modules/everyday/word-count/WordCountCalculator").then((m: any) => ({ default: m.WordCountCalculator || (() => null) }))),
  Base64Form: lazy(() => import("../../../modules/everyday/base64/Base64Encoder").then((m: any) => ({ default: m.Base64Encoder || (() => null) }))),
  EVChargingForm: lazy(() => import("../../../modules/everyday/ev-charging/EVChargingCalculator").then((m: any) => ({ default: m.EVChargingCalculator || (() => null) }))),
  LengthUnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "length" }) }))),
  WeightUnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "weight" }) }))),
  SpeedUnitForm:  lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "speed" }) }))),
  DataUnitForm:   lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "data" }) }))),
  AreaUnitForm:   lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "area" }) }))),
  TimeZoneForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.TimeZoneForm || (() => null) }))),
  ReadingTimeForm: lazy(() => import('../forms/MathForms').then((m: any) => ({ default: m.ReadingTimeForm || (() => null) }))),
};

export const utilityForms = {
  "area-calculator":                   Utility.AreaForm,
  "length-converter":                  Utility.LengthUnitForm,
  "weight-converter":                  Utility.WeightUnitForm,
  "temperature-converter":             Utility.TemperatureForm,
  "speed-converter":                   Utility.SpeedUnitForm,
  "data-storage-converter":            Utility.DataUnitForm,
  "area-converter":                    Utility.AreaUnitForm,
  "age-calculator":                    Utility.AgeForm,
  "date-difference-calculator":        Utility.DateDiffForm,
  "countdown-calculator":              Utility.CountdownForm,
  "work-hours-calculator":             Utility.WorkHoursForm,
  "fuel-cost-calculator":              Utility.FuelForm,
  "random-number-generator":           Utility.RandomForm,
  "password-generator":                Utility.PasswordForm,
  "roman-numeral-converter":           Utility.RomanForm,
  "word-counter":                      Utility.WordCountForm,
  "base64-encoder":                    Utility.Base64Form,
  "time-zone-converter":               Utility.TimeZoneForm,
  "ev-charging-calculator":            Utility.EVChargingForm,
  "reading-time-calculator":           Utility.ReadingTimeForm,
};
