import { lazy } from "react";

const Utility = {
  UnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.UnitForm }))),
  AreaForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.AreaForm }))),
  TemperatureForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.TemperatureForm }))),
  AgeForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.AgeForm }))),
  DateDiffForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.DateDiffForm }))),
  CountdownForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.CountdownForm }))),
  WorkHoursForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.WorkHoursForm }))),
  FuelForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.FuelForm }))),
  RandomForm: lazy(() => import("../../../modules/everyday/random/RandomGenerator.tsx").then((m: any) => ({ default: m.RandomGenerator }))),
  PasswordForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.PasswordForm }))),
  RomanForm: lazy(() => import("../../../modules/conversion/roman/RomanConverter.tsx").then((m: any) => ({ default: m.RomanConverter }))),
  WordCountForm: lazy(() => import("../../../modules/everyday/word-count/WordCountCalculator.tsx").then((m: any) => ({ default: m.WordCountCalculator }))),
  Base64Form: lazy(() => import("../../../modules/everyday/base64/Base64Encoder.tsx").then((m: any) => ({ default: m.Base64Encoder }))),
  EVChargingForm: lazy(() => import("../../../modules/everyday/ev-charging/EVChargingCalculator.tsx").then((m: any) => ({ default: m.EVChargingCalculator }))),
  LengthUnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "length" }) }))),
  WeightUnitForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "weight" }) }))),
  SpeedUnitForm:  lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "speed" }) }))),
  DataUnitForm:   lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "data" }) }))),
  AreaUnitForm:   lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: () => m.UnitForm({ type: "area" }) }))),
  TimeZoneForm: lazy(() => import('../forms/UtilityForms').then((m: any) => ({ default: m.TimeZoneForm }))),
};

export const utilityForms = {
  "area-calculator":                   Utility.AreaForm,
  "length-converter":                  Utility.LengthUnitForm,
  "weight-converter":                  Utility.WeightUnitForm,
  "temperature-converter":             Utility.TemperatureForm,
  "speed-converter":                   Utility.SpeedUnitForm,
  "data-storage-converter":            Utility.DataUnitForm,
  "area-converter":                    Utility.AreaUnitForm,
  "age-calculator":                    Utility.AgeForm,
  "date-difference-calculator":        Utility.DateDiffForm,
  "countdown-calculator":              Utility.CountdownForm,
  "work-hours-calculator":             Utility.WorkHoursForm,
  "fuel-cost-calculator":              Utility.FuelForm,
  "random-number-generator":           Utility.RandomForm,
  "password-generator":                Utility.PasswordForm,
  "roman-numeral-converter":           Utility.RomanForm,
  "word-counter":                      Utility.WordCountForm,
  "base64-encoder":                    Utility.Base64Form,
  "time-zone-converter":               Utility.TimeZoneForm,
  "ev-charging-calculator":            Utility.EVChargingForm,
};
